Am = 2;
fm = 50;
t = 0:0.00001:10;
fc = 500;
f = 0 : length(t);
beta = 4;
Ac = 10;
c_t = Ac * cos(2*pi*fc*t);
m_t = Am * cos(2*pi*fm*t);
Im = zeros(1,length(t));
s_fm = zeros(1,length(t));
% for i = 1 : length(t)
%     for x = i : 1
%         Im(i) = Im(i) + m_t(x) * t(x);
%     end;
%     %s_fm(i) = Ac * cos(2*pi*fc*t(i) + 2*pi*kf*Im(i));
%end;
s_fm = Ac * cos(2*pi*fc*t + beta*sin(2*pi*fm*t));
subplot(3,1,1);
%figure(1);
plot(t,m_t);
axis([0,0.1,-6, 6]);
xlabel('time,t');
ylabel('amp(m(t))');
title('m(t) - 50 Hz');
subplot(3,1,2);
%figure(2);
plot(t,c_t);
axis([0,0.1,-11,11]);
xlabel('time,t');
ylabel('amp(c(t))');
title('c(t) - 500 Hz');
subplot(3,1,3);
%figure(3);
plot(t,s_fm);
axis([0,0.1,-11, 11]);
xlabel('time,t');
ylabel('amp(s_fm(t))');
title('s_m(t)');
figure(2);
nfft = 1024;
M_w = fft(m_t,nfft);
C_w = fft(c_t,nfft);
S_fm_w = fft(s_fm,nfft);
M_w = M_w(1:nfft/2);
C_w = C_w(1:nfft/2);
S_fm_w = S_fm_w(1:nfft/2);
M_wx = abs(M_w);
C_wx = abs(C_w);
S_fm_wx = abs(S_fm_w);
f = (0:nfft/2-1)*1/0.00001/nfft;
figure(2);
subplot(3,1,1);
plot(f,M_wx);
axis([0,10000,0,1000]);
xlabel('f');
ylabel('M(w)');
title('Message Spectrum');
subplot(3,1,2);
plot(f,C_wx);
axis([0,10000,0,5000]);
xlabel('f');
ylabel('C(w)');
title('Carrier Spectrum');
subplot(3,1,3);
plot(f,S_fm_wx);
axis([0,10000,0,5000]);
xlabel('f');
ylabel('S_fm(w)');
title('Frequency modulated signal Spectrum');

