x = input('Enter values of x(n) ');
y = input('Enter values of y(n) ');
N1 = length(x);
N2 = length(y);
N = N1+N2-1;
x = [x zeros(1,N-N1)];
y = [y zeros(1,N-N2)];
xk = dft1(x);
yk = dft1(y);
zk = zeros(1, N);
%xk = [xk zeros(1,N)];
%yk = [yk zeros(1,N)];
for i1 =(1:N)
    zk(i1) = xk(i1) .* yk(i1);
end;
z = idft1(zk);
t = 1:N;
subplot(3,1,1);
stem(x);
xlabel('n');
ylabel('X values');
title('Plot of x(n)');
subplot(3,1,2);
stem(y);
xlabel('n');
ylabel('Y values');
title('Plot of y(n)');
subplot(3,1,3);
stem(z);
xlabel('n');
ylabel('Z values');
title('Plot of z(n) - the linear convolution of x(n) & y(n)');